### ISSUE TITLE
Fix .env relative path

### ISSUE THREAD

**Issue by rluders** [johnull/todo-golang#3]
https://github.com/johnull/todo-golang/blob/df8504f6ba2f092f48c902b38a11346e60d48e78/cmd/webapp/main.go#L12

It isn't recommended to have the `.env`  path, or any path, hard coded as relative path. You must hard code a fixed path such `./config/.env` or `./.env` or even to use an environment variable to indicate the path for it. But normally the .env files lives at the same folder or at least working_dir as the application.

**Comment by johnull** [comment]
because of my own cluelessness, my ConnectDB function is being called before main(), so i put the Load() in internal/database/connection.go
